### ISSUE TITLE
When trying to run the demo file on custom file, it shows Digital filter critical frequencies must be 0 < Wn < 1

### ISSUE THREAD

**Issue by version0chiro** [phuselab/pyVHR#2]

**Comment by version0chiro** [comment]
I was able to solve this by using numpy clip for now but if anyone has any other kind of advice for it it would be great

**Comment by version0chiro** [comment]
closing this issue as no kind of reply was being recieved

**Comment by vcuculo** [comment]
@version0chiro thanks for your issue! Please reformat the issue in order to be able to reproduce the bug or the warning and help you in an effective way. [Here you can find](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f) some best practices for writing proper GitHub issue. Thanks!

**Comment by vcuculo** [comment]
Closed since no updates received from the author.
