### ISSUE TITLE
Google Colab notebook

### ISSUE THREAD

**Issue by ghost** [phuselab/pyVHR#25]
Can this pyVHR be used in the Google Colab? Please advice how to use the framework in Google Colab.

**Comment by joewilliams1124** [comment]
Hey!

I've been having some similar issues, trying to set up the environment to run PyVHR. I've been following a tutorial to set up miniconda in Colab and then recreate the (yml) environment in the base environment. However, I can't seem to get it to work - possibly due to a mismatch in the Python version between the yml environment and Colab. I've been following this tutorial: https://towardsdatascience.com/conda-google-colab-75f7c867a522

Maybe someone could help me out with getting the environment up and running, maybe using pip?

Many thanks!
Joe
