### ISSUE TITLE
The value of BVP is reaching over thousand ranges as the fps goes forward. If I am looking to utilize this with real life application without having dataset for ecg values, how reliable is the data

### ISSUE THREAD

**Issue by version0chiro** [phuselab/pyVHR#3]

**Comment by vcuculo** [comment]
@version0chiro thanks for your issue! Please reformat the issue in order to be able to reproduce the bug or the warning and help you in an effective way. [Here you can find](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f) some best practices for writing proper GitHub issue. Thanks!

**Comment by vcuculo** [comment]
Closed since no updates received from the author.
