### ISSUE TITLE
Bypassing Face Detection for precropped skin videos?

### ISSUE THREAD

**Issue by hashtagSELFIE** [phuselab/pyVHR#30]
First things first, I really appreciate on the work on open and easily avalible rPPG methods.

One thing that I have wondered is, for my specific usecase i will need the skin region that I have manually cropped (squared video of manually cropped skins, no background), I really wondered if there is anyways to skip either face region selection part, Or selecting entire video as a region. That would really help simplifies things a lot.

Kind regards.

**Comment by aledamelio** [comment]
Hi @hashtagSELFIE 
thanks for the interest in this project. Recently the framework has been updated in order to enable the introduction of methods relying on the RAW frames as input (e.g. Deep Learning based approaches). I guess what you need is the extract_raw() function from the pyVHR's SignalProcessing() class. Try having a look at the pyVHR_demo_deep.ipynb notebook for an example.

Best Regards,
Alessandro
