### ISSUE TITLE
BPFilter fails if any windows have had all patches rejected

### ISSUE THREAD

**Issue by Benjabby** [phuselab/pyVHR#44]
When using the patch RGB threshold filter; if all patches are rejected this results in an empty window. Some filters and RPPG calculation methods can deal with this; they simply 'propagate' the empty window while processing all other windows fine. However the BPFilter cannot deal with it and throws an error. 

This can be easily replicated by using the video ID 0 of the LGI-PPGI dataset in the demo notebook and using the RGB threshold settings as in the hollistic.cfg file.

Any thoughts on how best to deal with this? I can think of two options, either that a window never rejects all patches by choosing at least one signal that has breaks the threshold least eggregiously, or by outputting a default signal somewhere along the line (either when all patches are rejected or as an output of the BVPFilter)

**Comment by giulianogrossi** [comment]
We have recently corrected this critical aspect of RGB color thresholds a bit, preventing empty lists from being propagated because no patch meets the constraints. Of course, with very restrictive thresholds the risk is that no patch will produce values within the range, thus propagating empty lists. The only possible remedy is to set correct values (possibly at the maximum possible range, i.e. 0 and 255, for very dark or bright videos) in the .cfg configuration file.  Clearly the RGB traces would suffer and probably induce more estimation errors, but this should not cause the calculation to fail.

Instead, for the file with ID = 0 of the LGI-PPGI dataset (and really for no other file of all the datasets mentioned in the articles) we have never encountered problems with thresholds such as, for example, those used in the demo notebook. 

Please keep us updated if the tests continue to give problems and we will provide more effective interventions! Thank you for your support.

cheers
Giuliano
